// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ijbX9dfpBRbW1FGSgs1NJo
// Component: SfDwl07Aj4uB

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import NavBar from "../../NavBar"; // plasmic-import: 38U0KJJ_izLvF0/component
import ContainerProduk from "../../ContainerProduk"; // plasmic-import: Drd5MExytXv/component
import Button from "../../Button"; // plasmic-import: z08NHQzGDufhl_/component
import ProductCard from "../../ProductCard"; // plasmic-import: be4gyluQ_9OJzR/component
import Rating from "../../Rating"; // plasmic-import: JRf21XH4cTf7V-/component
import Value from "../../Value"; // plasmic-import: 3bRucgJCclHNht/component
import Footer from "../../Footer"; // plasmic-import: TjbIATQS4AqoQO/component

import { useScreenVariants as useScreenVariantsbvEuI4Yp87Tgs } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: BV_euI4yp87tgs/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic_antd_5_hostless.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic_plasmic_rich_components.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic_chipsia.module.css"; // plasmic-import: ijbX9dfpBRbW1FGSgs1NJo/projectcss
import sty from "./PlasmicProducts.module.css"; // plasmic-import: SfDwl07Aj4uB/css

import MenuIcon from "./icons/PlasmicIcon__Menu"; // plasmic-import: vIBh7hkedAKVLS/icon
import RightArrowIcon from "./icons/PlasmicIcon__RightArrow"; // plasmic-import: PS6DVWNrsATME2/icon
import MedalIcon from "./icons/PlasmicIcon__Medal"; // plasmic-import: rGAFqrIjwFkcZM/icon
import LeafIcon from "./icons/PlasmicIcon__Leaf"; // plasmic-import: sxhoIq9e99bhcn/icon
import MoneySvgrepoComsvgIcon from "./icons/PlasmicIcon__MoneySvgrepoComsvg"; // plasmic-import: ra_o6xwOHS/icon
import PeaceIcon from "./icons/PlasmicIcon__Peace"; // plasmic-import: X6eB28EOD3seMa/icon

createPlasmicElementProxy;

export type PlasmicProducts__VariantMembers = {};
export type PlasmicProducts__VariantsArgs = {};
type VariantPropType = keyof PlasmicProducts__VariantsArgs;
export const PlasmicProducts__VariantProps = new Array<VariantPropType>();

export type PlasmicProducts__ArgsType = {
  container42?: React.ReactNode;
};
type ArgPropType = keyof PlasmicProducts__ArgsType;
export const PlasmicProducts__ArgProps = new Array<ArgPropType>("container42");

export type PlasmicProducts__OverridesType = {
  root?: p.Flex<"main">;
  navBar?: p.Flex<typeof NavBar>;
  container4?: p.Flex<"div">;
  h1?: p.Flex<"h1">;
  containerProduk?: p.Flex<typeof ContainerProduk>;
  container42?: p.Flex<"div">;
  container5?: p.Flex<"div">;
  productCard7?: p.Flex<typeof ProductCard>;
  productCard8?: p.Flex<typeof ProductCard>;
  productCard9?: p.Flex<typeof ProductCard>;
  productCard10?: p.Flex<typeof ProductCard>;
  productCard11?: p.Flex<typeof ProductCard>;
  productCard12?: p.Flex<typeof ProductCard>;
  container433?: p.Flex<"div">;
  footer?: p.Flex<typeof Footer>;
};

export interface DefaultProductsProps {}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicProducts__RenderFunc(props: {
  variants: PlasmicProducts__VariantsArgs;
  args: PlasmicProducts__ArgsType;
  overrides: PlasmicProducts__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;
  const __nextRouter = useNextRouter();

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};

  const [$queries, setDollarQueries] = React.useState({});

  const stateSpecs = React.useMemo(
    () => [
      {
        path: "productCard7.entryidvar",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      },
      {
        path: "productCard8.entryidvar",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      },
      {
        path: "productCard9.entryidvar",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      },
      {
        path: "productCard10.entryidvar",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      },
      {
        path: "productCard11.entryidvar",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      },
      {
        path: "productCard12.entryidvar",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = p.useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries,
    $refs
  });

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsbvEuI4Yp87Tgs()
  });

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary_large_image" />
        <title key="title">{PlasmicProducts.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicProducts.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicProducts.pageMetadata.title}
        />
        <meta
          key="description"
          name="description"
          content={PlasmicProducts.pageMetadata.description}
        />
        <meta
          key="og:description"
          property="og:description"
          content={PlasmicProducts.pageMetadata.description}
        />
        <meta
          key="twitter:description"
          name="twitter:description"
          content={PlasmicProducts.pageMetadata.description}
        />
        <meta
          key="og:image"
          property="og:image"
          content={PlasmicProducts.pageMetadata.ogImageSrc}
        />
        <meta
          key="twitter:image"
          name="twitter:image"
          content={PlasmicProducts.pageMetadata.ogImageSrc}
        />
        <link ref="canonical" href={PlasmicProducts.pageMetadata.canonical} />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <main
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            plasmic_plasmic_rich_components_css.plasmic_tokens,
            sty.root
          )}
        >
          <NavBar
            data-plasmic-name={"navBar"}
            data-plasmic-override={overrides.navBar}
            className={classNames("__wab_instance", sty.navBar)}
          />

          <section className={classNames(projectcss.all, sty.section__mLMt)}>
            <div
              data-plasmic-name={"container4"}
              data-plasmic-override={overrides.container4}
              className={classNames(projectcss.all, sty.container4)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__wvxft)}>
                <h1
                  data-plasmic-name={"h1"}
                  data-plasmic-override={overrides.h1}
                  className={classNames(
                    projectcss.all,
                    projectcss.h1,
                    projectcss.__wab_text,
                    sty.h1
                  )}
                >
                  {"Product of Chipsia"}
                </h1>
              </div>
            </div>
            <ContainerProduk
              data-plasmic-name={"containerProduk"}
              data-plasmic-override={overrides.containerProduk}
              className={classNames("__wab_instance", sty.containerProduk)}
            />
          </section>
          <section className={classNames(projectcss.all, sty.section__icXf0)}>
            <div
              data-plasmic-name={"container42"}
              data-plasmic-override={overrides.container42}
              className={classNames(projectcss.all, sty.container42)}
            >
              {p.renderPlasmicSlot({
                defaultContents: (
                  <div
                    className={classNames(projectcss.all, sty.freeBox__ygEpj)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___9W1O
                      )}
                    >
                      {"Why Import From Us ?"}
                    </div>
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__vozse
                      )}
                      colors={"link" as const}
                      endIcon={
                        <RightArrowIcon
                          className={classNames(projectcss.all, sty.svg__ggkJn)}
                          role={"img"}
                        />
                      }
                      showEndIcon={true}
                      submitsForm={true}
                    >
                      {"See more"}
                    </Button>
                  </div>
                ),
                value: args.container42
              })}
            </div>
            <div
              data-plasmic-name={"container5"}
              data-plasmic-override={overrides.container5}
              className={classNames(projectcss.all, sty.container5)}
            >
              {true ? (
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__inTYk)}
                >
                  <ProductCard
                    data-plasmic-name={"productCard7"}
                    data-plasmic-override={overrides.productCard7}
                    img={{
                      src: "/plasmic/chipsia/images/shoe14.png",
                      fullWidth: 840,
                      fullHeight: 840,
                      aspectRatio: undefined
                    }}
                    onEntryidvarChange={p.generateStateOnChangeProp($state, [
                      "productCard7",
                      "entryidvar"
                    ])}
                    tags={
                      <Button
                        colors={"lightGray" as const}
                        size={"small" as const}
                        submitsForm={true}
                      >
                        {"New"}
                      </Button>
                    }
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__uEw2T
                      )}
                    >
                      {"ADIDAS ULTRABOOST DNA X LEGO\u00ae PLATES SHOES"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__xuatH
                      )}
                    >
                      {"If you can dream it, you can build it."}
                    </div>
                  </ProductCard>
                  <ProductCard
                    data-plasmic-name={"productCard8"}
                    data-plasmic-override={overrides.productCard8}
                    className={classNames("__wab_instance", sty.productCard8)}
                    img={{
                      src: "/plasmic/chipsia/images/shoe15.png",
                      fullWidth: 864,
                      fullHeight: 1080,
                      aspectRatio: undefined
                    }}
                    onEntryidvarChange={p.generateStateOnChangeProp($state, [
                      "productCard8",
                      "entryidvar"
                    ])}
                    tags={
                      <Button
                        colors={"lightGray" as const}
                        size={"small" as const}
                        submitsForm={true}
                      >
                        {"New"}
                      </Button>
                    }
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__uamnv
                      )}
                    >
                      {"Nike Air Zoom Pegasus 38"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__iHLvY
                      )}
                    >
                      {"If you can dream it, you can build it."}
                    </div>
                  </ProductCard>
                  <ProductCard
                    data-plasmic-name={"productCard9"}
                    data-plasmic-override={overrides.productCard9}
                    className={classNames("__wab_instance", sty.productCard9)}
                    img={{
                      src: "/plasmic/chipsia/images/shoe16.png",
                      fullWidth: 840,
                      fullHeight: 840,
                      aspectRatio: undefined
                    }}
                    onEntryidvarChange={p.generateStateOnChangeProp($state, [
                      "productCard9",
                      "entryidvar"
                    ])}
                    tags={
                      <Button
                        colors={"lightGray" as const}
                        size={"small" as const}
                        submitsForm={true}
                      >
                        {"New"}
                      </Button>
                    }
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__fcZi
                      )}
                    >
                      {"Club C 85 Vintage Men's Shoes"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__d7B0A
                      )}
                    >
                      {"If you can dream it, you can build it."}
                    </div>
                  </ProductCard>
                  <ProductCard
                    data-plasmic-name={"productCard10"}
                    data-plasmic-override={overrides.productCard10}
                    className={classNames("__wab_instance", sty.productCard10)}
                    img={{
                      src: "/plasmic/chipsia/images/shoe17.png",
                      fullWidth: 864,
                      fullHeight: 1080,
                      aspectRatio: undefined
                    }}
                    onEntryidvarChange={p.generateStateOnChangeProp($state, [
                      "productCard10",
                      "entryidvar"
                    ])}
                    tags={
                      <Button
                        colors={"lightGray" as const}
                        size={"small" as const}
                        submitsForm={true}
                      >
                        {"New"}
                      </Button>
                    }
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__vNfp
                      )}
                    >
                      {"Nike Air Max Genome"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___3YqbV
                      )}
                    >
                      {"If you can dream it, you can build it."}
                    </div>
                  </ProductCard>
                  <ProductCard
                    data-plasmic-name={"productCard11"}
                    data-plasmic-override={overrides.productCard11}
                    className={classNames("__wab_instance", sty.productCard11)}
                    img={{
                      src: "/plasmic/chipsia/images/shoe18.png",
                      fullWidth: 840,
                      fullHeight: 840,
                      aspectRatio: undefined
                    }}
                    onEntryidvarChange={p.generateStateOnChangeProp($state, [
                      "productCard11",
                      "entryidvar"
                    ])}
                    tags={
                      <Button
                        colors={"lightGray" as const}
                        size={"small" as const}
                        submitsForm={true}
                      >
                        {"New"}
                      </Button>
                    }
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__hQkmY
                      )}
                    >
                      {"ULTRABOOST DNA 1.0 SHOES"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___4Fs4J
                      )}
                    >
                      {"If you can dream it, you can build it."}
                    </div>
                  </ProductCard>
                  <ProductCard
                    data-plasmic-name={"productCard12"}
                    data-plasmic-override={overrides.productCard12}
                    className={classNames("__wab_instance", sty.productCard12)}
                    img={{
                      src: "/plasmic/chipsia/images/shoe19.png",
                      fullWidth: 864,
                      fullHeight: 1080,
                      aspectRatio: undefined
                    }}
                    onEntryidvarChange={p.generateStateOnChangeProp($state, [
                      "productCard12",
                      "entryidvar"
                    ])}
                    tags={
                      <Button
                        colors={"lightGray" as const}
                        size={"small" as const}
                        submitsForm={true}
                      >
                        {"New"}
                      </Button>
                    }
                  />
                </p.Stack>
              ) : null}
            </div>
          </section>
          <section className={classNames(projectcss.all, sty.section__acIiD)}>
            <p.Stack
              as={"div"}
              data-plasmic-name={"container433"}
              data-plasmic-override={overrides.container433}
              hasGap={true}
              className={classNames(projectcss.all, sty.container433)}
            >
              <div className={classNames(projectcss.all, sty.column__oYt03)}>
                <Value
                  center={true}
                  children2={
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button___4JP2
                      )}
                      colors={"black" as const}
                      endIcon={
                        <RightArrowIcon
                          className={classNames(projectcss.all, sty.svg__qFrV)}
                          role={"img"}
                        />
                      }
                      rounded={true}
                      size={"large" as const}
                      submitsForm={true}
                    >
                      {"Read our letter"}
                    </Button>
                  }
                  className={classNames("__wab_instance", sty.value__czaeF)}
                  icon={
                    <MedalIcon
                      className={classNames(projectcss.all, sty.svg__qXMv0)}
                      role={"img"}
                    />
                  }
                  topBottom={true}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__u7Wfv
                    )}
                  >
                    {"We guarantee everything we sell."}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__fDxRg
                    )}
                  >
                    {
                      "Every product we sell, tempeh chips, banana chips, cassava chips, and emping chips also other products, are made from fresh ingredients with legacy recipes. so you will be satisfied with the product you received"
                    }
                  </div>
                  <Button
                    className={classNames("__wab_instance", sty.button__q16Sn)}
                    colors={"link" as const}
                    submitsForm={true}
                  >
                    {"View guarantee"}
                  </Button>
                </Value>
              </div>
              <div className={classNames(projectcss.all, sty.column__gScDh)}>
                <Value
                  center={true}
                  children2={
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__u7Ret
                      )}
                      colors={"black" as const}
                      endIcon={
                        <RightArrowIcon
                          className={classNames(projectcss.all, sty.svg__tqcay)}
                          role={"img"}
                        />
                      }
                      rounded={true}
                      size={"large" as const}
                      submitsForm={true}
                    >
                      {"Read our letter"}
                    </Button>
                  }
                  className={classNames("__wab_instance", sty.value__m8DeL)}
                  icon={
                    <LeafIcon
                      className={classNames(projectcss.all, sty.svg__s0XkD)}
                      role={"img"}
                    />
                  }
                  topBottom={true}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__rj6Mh
                    )}
                  >
                    {"100 % organic and Plant based"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___1MKnm
                    )}
                  >
                    {
                      "The market for our product is increasing rapidly in your country. Our chips Product made from fresh and natural plant-based ingredients, so it's healthy and can become an alternative for people who are vegetarian or just want to consume healthy but  tasty snacks"
                    }
                  </div>
                  <Button
                    className={classNames("__wab_instance", sty.button___5NAk)}
                    colors={"link" as const}
                    submitsForm={true}
                  />
                </Value>
              </div>
              <div className={classNames(projectcss.all, sty.column__z8Gk)}>
                <Value
                  center={true}
                  children2={
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__xquaQ
                      )}
                      colors={"black" as const}
                      endIcon={
                        <RightArrowIcon
                          className={classNames(projectcss.all, sty.svg__rqeB)}
                          role={"img"}
                        />
                      }
                      rounded={true}
                      size={"large" as const}
                      submitsForm={true}
                    >
                      {"Read our letter"}
                    </Button>
                  }
                  className={classNames("__wab_instance", sty.value__irAiO)}
                  icon={
                    <MoneySvgrepoComsvgIcon
                      className={classNames(projectcss.all, sty.svg__jPSd)}
                      role={"img"}
                    />
                  }
                  topBottom={true}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__mb6Vm
                    )}
                  >
                    {"Reap High Profit by becoming importer"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___8WVyu
                    )}
                  >
                    {
                      "Our product is in high demand for the export market, now it's your turn to reap high profit by becoming an importer of our products such as tempeh chips, banana chips, emping chips, and cassava chips in your country "
                    }
                  </div>
                  <Button
                    className={classNames("__wab_instance", sty.button__qtQ7U)}
                    colors={"link" as const}
                    submitsForm={true}
                  />
                </Value>
              </div>
              <div className={classNames(projectcss.all, sty.column__mCt9)}>
                <Value
                  center={true}
                  children2={
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__qfGr1
                      )}
                      colors={"black" as const}
                      endIcon={
                        <RightArrowIcon
                          className={classNames(
                            projectcss.all,
                            sty.svg___93DRe
                          )}
                          role={"img"}
                        />
                      }
                      rounded={true}
                      size={"large" as const}
                      submitsForm={true}
                    >
                      {"Read our letter"}
                    </Button>
                  }
                  className={classNames("__wab_instance", sty.value__xOdV7)}
                  icon={
                    <PeaceIcon
                      className={classNames(projectcss.all, sty.svg__eiJi8)}
                      role={"img"}
                    />
                  }
                  topBottom={true}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__arc6E
                    )}
                  >
                    {"We give back for every sale."}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__uHsGg
                    )}
                  >
                    {
                      "we give back to our people. By Importing from us you also contribute to local communities of traditional Indonesian food producers, because we only produce our product by empowering local Indonesian people"
                    }
                  </div>
                  <Button
                    className={classNames("__wab_instance", sty.button___5Mmzp)}
                    colors={"link" as const}
                    submitsForm={true}
                  />
                </Value>
              </div>
            </p.Stack>
          </section>
          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />
        </main>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "navBar",
    "container4",
    "h1",
    "containerProduk",
    "container42",
    "container5",
    "productCard7",
    "productCard8",
    "productCard9",
    "productCard10",
    "productCard11",
    "productCard12",
    "container433",
    "footer"
  ],
  navBar: ["navBar"],
  container4: ["container4", "h1"],
  h1: ["h1"],
  containerProduk: ["containerProduk"],
  container42: ["container42"],
  container5: [
    "container5",
    "productCard7",
    "productCard8",
    "productCard9",
    "productCard10",
    "productCard11",
    "productCard12"
  ],
  productCard7: ["productCard7"],
  productCard8: ["productCard8"],
  productCard9: ["productCard9"],
  productCard10: ["productCard10"],
  productCard11: ["productCard11"],
  productCard12: ["productCard12"],
  container433: ["container433"],
  footer: ["footer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "main";
  navBar: typeof NavBar;
  container4: "div";
  h1: "h1";
  containerProduk: typeof ContainerProduk;
  container42: "div";
  container5: "div";
  productCard7: typeof ProductCard;
  productCard8: typeof ProductCard;
  productCard9: typeof ProductCard;
  productCard10: typeof ProductCard;
  productCard11: typeof ProductCard;
  productCard12: typeof ProductCard;
  container433: "div";
  footer: typeof Footer;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicProducts__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicProducts__VariantsArgs;
    args?: PlasmicProducts__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicProducts__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicProducts__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicProducts__ArgProps,
          internalVariantPropNames: PlasmicProducts__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicProducts__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicProducts";
  } else {
    func.displayName = `PlasmicProducts.${nodeName}`;
  }
  return func;
}

export const PlasmicProducts = Object.assign(
  // Top-level PlasmicProducts renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    navBar: makeNodeComponent("navBar"),
    container4: makeNodeComponent("container4"),
    h1: makeNodeComponent("h1"),
    containerProduk: makeNodeComponent("containerProduk"),
    container42: makeNodeComponent("container42"),
    container5: makeNodeComponent("container5"),
    productCard7: makeNodeComponent("productCard7"),
    productCard8: makeNodeComponent("productCard8"),
    productCard9: makeNodeComponent("productCard9"),
    productCard10: makeNodeComponent("productCard10"),
    productCard11: makeNodeComponent("productCard11"),
    productCard12: makeNodeComponent("productCard12"),
    container433: makeNodeComponent("container433"),
    footer: makeNodeComponent("footer"),

    // Metadata about props expected for PlasmicProducts
    internalVariantProps: PlasmicProducts__VariantProps,
    internalArgProps: PlasmicProducts__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "Chipsia Chips Products ",
      description:
        "import Supplier of Tempeh Chips, Banana Chips, Cassava Chips, Emping Chips and Tofu Chips ready for import to your country with High Quality, Lowest Price",
      ogImageSrc:
        "https://site-assets.plasmic.app/54f3ce18d37d548646a3665708ddddc8.jpg",
      canonical: "https://chipsia.com"
    }
  }
);

export default PlasmicProducts;
/* prettier-ignore-end */
